merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/add/', views.band_create, name='band-create'),    
    path('bands/<int:id>/', views.band_detail, name='band-detail'),   
    path('bands/<int:id>/change', views.band_change, name='band-change'),   
    path('bands/<int:id>/delete', views.band_delete, name='band-delete'),   
    path('about-us/', views.about),
    path('contact-us/', views.contact, name='contact'),
    path('email_sent/', views.email_sent, name='email-sent'),   
    path('listings/', views.listings_list, name="listing-list"),
    path('listings/<int:id>/', views.listings_detail, name='listing-detail'),   
    path('listings/add/', views.listings_create, name='listing-create'),    
    path('listings/<int:id>/change', views.listings_change, name='listing-change'),   
    path('listings/<int:id>/delete', views.listings_delete, name='listing-delete'),   

]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)    
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
    validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    def __str__(self):
        return f'{self.name}'

class Listings(models.Model):

    class Type(models.TextChoices):
        CD = "CD"
        VINYL = "VN"
        CASSETTE = "CS"
        DIGITAL = "DG"
        OTHER = "OT"

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000, default="Enter a description")
    sold = models.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)],
        null=True
    )
    type = models.fields.CharField(Type.choices, max_length=3, default=Type.OTHER)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listings

class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
   class Meta:
      model = Band
      exclude = ('active', 'official_homepage')  

class ListingsForm(forms.ModelForm):
   class Meta:
      model = Listings
      fields = '__all__' 

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band, Listings
from listings.forms import BandForm, ContactUsForm, ListingsForm
from django.core.mail import send_mail
from django.shortcuts import redirect

def band_list(request):
    bands = Band.objects.all()
    return render(request,
    'listings/band_list.html',
    {'bands': bands})

def band_detail(request, id):
  band = Band.objects.get(id=id)
  return render(request,
          'listings/band_detail.html',
          {'band': band}) 

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('band-detail', band.id)

def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/band_delete.html',
                    {'band': band})
        

def band_change(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-change', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                'listings/band_change.html',
                {'form': form})

def about(request):
    return render(request,
    'listings/about.html')

def contact(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
        )
            return redirect('email-sent') 
    else:
        form = ContactUsForm()

    return render(request,
                'listings/contact.html',
                {'form': form})

def email_sent(request):
    return render(request,
    'listings/email_sent.html')

def listings_list(request):
    listings = Listings.objects.all()
    return render(request,
    'listings/listings_list.html',
    {'listings': listings})

def listings_detail(request, id):
    listing = Listings.objects.get(id=id)
    return render(request,
            'listings/listings_detail.html',
            {'listing': listing}) 

def listings_create(request):
    if request.method == 'POST':
        form = ListingsForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect('listing-detail', listing.id)

    else:
        form = ListingsForm()

    return render(request,
            'listings/listings_create.html',
            {'form': form})

def listings_change(request, id):
    listing = Listings.objects.get(id=id)

    if request.method == 'POST':
        form = ListingsForm(request.POST, instance=listing)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('listing-change', listing.id)
    else:
        form = ListingsForm(instance=listing)

    return render(request,
                'listings/listings_change.html',
                {'form': form})

def listings_delete(request, id):
    listing = Listings.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        listing.delete()
        # rediriger vers la liste des groupes
        return redirect('listing-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/listings_delete.html',
                    {'listing': listing})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>À propos</h1> 
    <p>Nous adorons merch ! <3 </p>

{% endblock %}

merchex/listings/templates/listings/band_change.html
{% extends 'listings/base.html' %}

{% block content %}


    <h1>Mise à jour du groupe</h1>

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
    </form>

{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Créer un nouveau groupe</h1>

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
    </form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
    <li> Annonce : 
        <ul>
        {% for listing in band.listings_set.all %} 
            <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a></li>
        {% endfor%} 
        </ul>
    </li>
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-change' band.id %}">Modifier ce groupe</a>
<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>
<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>
<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
<ul>
 {% for band in bands %}
    <li>
        <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
        - <a href="{% url 'band-change' band.id %}">[modifier]</a>
    </li>
 {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}

<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'listing-list' %}">Annonces</a>
            <a href="{% url 'contact' %}">Contact</a>
        </nav>
        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Contactez nous</h1> 
    <p> Ici !!</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}        
        <input type="submit" value="Envoyer">
    </form>

{% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Email envoyé!</h1> 

{% endblock %}

merchex/listings/templates/listings/listings_change.html
{% extends 'listings/base.html' %}

{% block content %}


    <h1>Mise à jour de l'annonce</h1>

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
    </form>

{% endblock %}

merchex/listings/templates/listings/listings_create.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Créer une nouvelle annonce</h1>

    <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
    </form>

{% endblock %}

merchex/listings/templates/listings/listings_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer l'annonce</h1>

<p>Etes-vous sûr de vouloir supprimer l'annonce : {{ listing.title }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/listings_detail.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Annonce</h1>
    <p>Mes annonces sont:</p>
    <ul>
        <li>Titre : {{ listing.title }}</li>
        <li>Année : {{ listing.year }}</li>
        <li>Description : {{ listing.description }}</li>
        <li>Actif : {{ listing.sold |yesno }}</li>
        <li>Band : {{ listing.band }}</li>
    </ul>

    <a href="{% url 'listing-change' listing.id %}">Modifier cette annonce</a>   
    <a href="{% url 'listing-delete' listing.id %}">Supprimer cette annonce</a>
    <a href="{% url 'listing-list' %}">Retour à toutes les annonces</a>


{% endblock %}
   

merchex/listings/templates/listings/listings_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Listing</h1>
<a href="{% url 'listing-create' %}">Créer une nouvelle annonce</a>
<ul>
 {% for listing in listings %}
    <li>
        <a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a>
        - <a href="{% url 'listing-change' listing.id %}">[modifier]</a>
    </li>
 {% endfor %}
</ul>

{% endblock %}